---
# ## Lesson 4 LABS:
# 1. Write a playbook that installs the httpd package on ansible2.example.com
# 2. Ensure that it is started and that the firewall is opened to allow access to it
# 3. Also create a file /var/www/html/index.html with some welcome text
# 4. Lastly, write a playbook that will undo all modifications

- hosts: a2
  tasks:
  - yum:
    name: httpd
    state: latest

  - firewalld:
    service: http
    permanent: yes
    state: enabled

  - systemd:
    state: started
    name: httpd
    enabled: yes
    
  - name: Copy using inline content
    copy:
    content: 'HELLO APACHE WORLD'
    dest: /var/www/html/index.html